version: '3.8'

services:
#  app:
#    image: taehun0858/kub-first-app:latest
#    container_name: delivery-app
#    restart: always
#    depends_on:
#      - postgres
#      - redis
#      - elasticsearch
#    environment:
#      JWT_SECRET_KEY: cKJdpO7vLICJY5NPUIATXQcf+r8rMDbCQYygd/fyY/s=
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/delivery
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: 0000
#      SPRING_DATA_REDIS_HOST: redis
#      SPRING_ELASTICSEARCH_URIS: http://elasticsearch:9200
#      GOOGLE_AI_STUDIO_API_KEY: AIzaSyCubzWfJPW9nozDXuJdkfc7vljrCi4bTnI
#      DB_PASSWORD: 1234
#    ports:
#      - "8080:8080"
#    networks:
#      - my-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres          # 사용자 이름
      POSTGRES_PASSWORD: 1234    # 비밀번호
      POSTGRES_DB: delivery          # 데이터베이스 이름
    ports:
      - "5432:5432"
    networks:
      - my-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - my-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.2
    command: >
      /bin/bash -c "
      elasticsearch-plugin install analysis-nori --batch &&
      /usr/local/bin/docker-entrypoint.sh"
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"  # Elasticsearch 메모리 설정
      xpack.security.enabled: false
      xpack.security.http.ssl.enabled: false
      xpack.security.transport.ssl.enabled: false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - my-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
volumes:
  esdata:

networks:
  my-network:
    driver: bridge
